# Docker Compose for local development
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AWS_REGION=us-east-1
    volumes:
      - ./backend/src:/app/backend/src
      - ./core/src:/app/core/src
    depends_on:
      - redis
      - dynamodb-local

  ml-algorithm:
    build:
      context: .
      dockerfile: Dockerfile.ml
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-1
    volumes:
      - ./ml-algorithm/src:/app/src
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8001:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  kinesis-local:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis,dynamodb,s3
      - DEBUG=1
    volumes:
      - kinesis_data:/var/lib/localstack

volumes:
  redis_data:
  dynamodb_data:
  kinesis_data:
